USE `shop`;

SET FOREIGN_KEY_CHECKS = 0;
DELETE FROM `product_images`;
DELETE FROM `products`;
DELETE FROM `product_categories`;
DELETE FROM `site_settings`;
DELETE FROM `site_nav_items`;
DELETE FROM `site_banners`;
DELETE FROM `site_benefits`;
DELETE FROM `content_pages`;
DELETE FROM `content_articles`;
DELETE FROM `team_members`;
DELETE FROM `partners`;
DELETE FROM `industries`;
DELETE FROM `videos`;
SET FOREIGN_KEY_CHECKS = 1;

INSERT INTO `site_settings` (`id`,`group_name`,`label`,`key`,`value`,`value_type`,`sort`,`status`,`created_at`,`updated_at`) VALUES
(1,'brand','Logo','logo_url','https://www.hbfittings.net/uploads/33800/logo.jpg','image',10,1,NOW(3),NOW(3)),
(2,'contact','Telephone','phone','+86-714-6387131','phone',10,1,NOW(3),NOW(3)),
(3,'contact','Phone / WhatsApp','whatsapp','+86-18271622836','phone',20,1,NOW(3),NOW(3)),
(4,'contact','Sales Email','email','summer@hbfittings.net','email',30,1,NOW(3),NOW(3)),
(5,'contact','Address','address','Xialu District, Guilin North Road, #16, Huangshi City, China','text',40,1,NOW(3),NOW(3)),
(6,'contact','Contact Page Image','contact_image_url','https://www.hbfittings.net/uploads/33800/index/3.jpg','image',50,1,NOW(3),NOW(3)),
(7,'footer','QR Code','qr_code_url','https://www.hbfittings.net/uploads/202133800/erwei80690420210702.jpg?size=180x0','image',10,1,NOW(3),NOW(3)),
(8,'home','Factory Video','home_video_url','https://www.youtube.com/watch?v=WfXRP5cPMo8','url',10,1,NOW(3),NOW(3)),
(9,'contact','Taiwan Company','taiwan_company','DENCO METAL PRODUCTS, INC','text',60,1,NOW(3),NOW(3)),
(10,'contact','Taiwan Address','taiwan_address','NO.279, MINQUAN RD., LUGANG TOWNSHIP, CHANGHUA COUNTY, TAIWAN 50548','text',70,1,NOW(3),NOW(3)),
(11,'contact','Taiwan Email','taiwan_email','denco_summer1@aliyun.com','email',80,1,NOW(3),NOW(3)),
(12,'contact','Taiwan Phone','taiwan_phone','+886-04-7762321','phone',90,1,NOW(3),NOW(3)),
(13,'seo','Site Name','site_name','Hubei Depo Valve and Fitting Co., Ltd.','text',10,1,NOW(3),NOW(3)),
(14,'social','Facebook','facebook_url','https://www.facebook.com/share/15vpiBrFqe/?mibextid=wwXIfr','url',10,1,NOW(3),NOW(3)),
(15,'social','LinkedIn','linkedin_url','http://linkedin.com/in/huang-shuangshuang-8757a8b0','url',20,1,NOW(3),NOW(3)),
(16,'design','Inner Page Hero','page_hero_url','https://www.hbfittings.net/uploads/202333800/ImgScroll/ba34c91d03-0f0f-41f5-ae7a-b5926ce5340d.jpg','image',10,1,NOW(3),NOW(3)),
(17,'design','Why Depo Background','why_background_url','https://www.hbfittings.net/uploads/202333800/ImgScroll/ba34c91d03-0f0f-41f5-ae7a-b5926ce5340d.jpg','image',20,1,NOW(3),NOW(3));

INSERT INTO `site_nav_items` (`id`,`parent_id`,`label`,`path`,`location`,`open_new`,`sort`,`status`,`created_at`,`updated_at`) VALUES
(1,0,'Home','/','header',0,10,1,NOW(3),NOW(3)),
(2,0,'About Us','/about-us','header',0,20,1,NOW(3),NOW(3)),
(3,0,'Products','/products','header',0,30,1,NOW(3),NOW(3)),
(4,0,'Customer Cases & News','/news','header',0,40,1,NOW(3),NOW(3)),
(5,0,'Knowledge','/knowledge','header',0,50,1,NOW(3),NOW(3)),
(6,0,'Contact Us','/contact-us','header',0,60,1,NOW(3),NOW(3)),
(7,0,'Video','/video','header',0,70,1,NOW(3),NOW(3)),
(8,0,'Feedback','/feedback','header',0,80,1,NOW(3),NOW(3)),
(9,0,'Blog','/blog','header',0,90,1,NOW(3),NOW(3)),
(21,2,'Company Profile','/page/company-profile','header',0,10,1,NOW(3),NOW(3)),
(22,2,'OEM','/page/oem','header',0,20,1,NOW(3),NOW(3)),
(23,2,'Materials','/page/materials','header',0,30,1,NOW(3),NOW(3)),
(24,2,'Service','/page/service','header',0,40,1,NOW(3),NOW(3)),
(25,2,'FAQ','/page/faq','header',0,50,1,NOW(3),NOW(3)),
(31,3,'Brass Fittings','/category/brass-fittings','header',0,10,1,NOW(3),NOW(3)),
(32,3,'Brass Instrument Valve','/category/brass-instrument-valve','header',0,20,1,NOW(3),NOW(3)),
(33,3,'Pressure Gauge Accessories','/category/pressure-gauge-accessories','header',0,30,1,NOW(3),NOW(3)),
(34,3,'Stainless Steel Valve','/category/stainless-steel-valve','header',0,40,1,NOW(3),NOW(3)),
(35,3,'Stainless Steel Ball Valve','/category/stainless-steel-ball-valve','header',0,50,1,NOW(3),NOW(3)),
(36,3,'Stainless Steel Fitting','/category/stainless-steel-fitting','header',0,60,1,NOW(3),NOW(3)),
(37,3,'Hydraulic Fittings','/category/hydraulic-fittings','header',0,70,1,NOW(3),NOW(3)),
(38,3,'Forged Pipe Fittings','/category/forged-pipe-fittings','header',0,80,1,NOW(3),NOW(3)),
(39,3,'Auto Parts Fittings','/category/auto-parts-fittings','header',0,90,1,NOW(3),NOW(3)),
(40,3,'Reusable Hose Fittings','/category/reusable-hose-fittings','header',0,100,1,NOW(3),NOW(3)),
(41,4,'Customer Orders Case','/news?category=Customer%20orders%20case','header',0,10,1,NOW(3),NOW(3)),
(42,4,'Shipment News','/news?category=shipment%20news','header',0,20,1,NOW(3),NOW(3)),
(43,4,'Industrial Knowledge','/news?category=industrial%20knowledge','header',0,30,1,NOW(3),NOW(3)),
(44,4,'Company Culture','/news?category=Company%20culture','header',0,40,1,NOW(3),NOW(3)),
(45,4,'Customer Feedback','/news?category=Customer%20feedback','header',0,50,1,NOW(3),NOW(3)),
(51,5,'Brass Valve','/knowledge?category=brass%20valve','header',0,10,1,NOW(3),NOW(3)),
(52,5,'Valve','/knowledge?category=Valve','header',0,20,1,NOW(3),NOW(3)),
(53,5,'Fittings','/knowledge?category=fittings','header',0,30,1,NOW(3),NOW(3)),
(54,5,'Material','/knowledge?category=material','header',0,40,1,NOW(3),NOW(3)),
(55,5,'Hydraulic Fittings','/knowledge?category=hydraulic%20fittings','header',0,50,1,NOW(3),NOW(3)),
(56,5,'Stainless Steel Valve','/knowledge?category=Stainless%20steel%20valve','header',0,60,1,NOW(3),NOW(3)),
(57,5,'Syphon Tube','/knowledge?category=Syphon%20tube','header',0,70,1,NOW(3),NOW(3)),
(101,0,'Home','/','footer',0,10,1,NOW(3),NOW(3)),
(102,0,'About Us','/about-us','footer',0,20,1,NOW(3),NOW(3)),
(103,0,'Products','/products','footer',0,30,1,NOW(3),NOW(3)),
(104,0,'Customer Cases & News','/news','footer',0,40,1,NOW(3),NOW(3)),
(105,0,'Knowledge','/knowledge','footer',0,50,1,NOW(3),NOW(3)),
(106,0,'Contact Us','/contact-us','footer',0,60,1,NOW(3),NOW(3)),
(107,0,'Video','/video','footer',0,70,1,NOW(3),NOW(3)),
(108,0,'Feedback','/feedback','footer',0,80,1,NOW(3),NOW(3)),
(109,0,'Blog','/blog','footer',0,90,1,NOW(3),NOW(3));

INSERT INTO `site_banners` (`id`,`title`,`subtitle`,`image_url`,`link_url`,`position`,`sort`,`status`,`created_at`,`updated_at`) VALUES
(1,'Precision Fittings for Demanding Fluid Systems','Brass and stainless steel valves and fittings engineered for reliable industrial performance.','https://www.hbfittings.net/uploads/202333800/ImgScroll/ba34c91d03-0f0f-41f5-ae7a-b5926ce5340d.jpg','/products','home',10,1,NOW(3),NOW(3)),
(2,'Professional Manufacturer Since 2007','OEM and ODM support, 100% inspection, international certifications and on-time delivery.','https://www.hbfittings.net/uploads/202133800/ImgScroll/ba202106241713226725344.jpg','/about-us','home',20,1,NOW(3),NOW(3)),
(3,'One Partner. A Complete Product Line.','From brass pipe fittings to high-pressure stainless steel instrumentation components.','https://www.hbfittings.net/uploads/202133800/ImgScroll/ba202106241713420093467.jpg','/feedback','home',30,1,NOW(3),NOW(3));

INSERT INTO `site_benefits` (`title`,`icon`,`sort`,`status`,`created_at`,`updated_at`) VALUES
('Experienced and focused on export since 2007','check',10,1,NOW(3),NOW(3)),
('Manufacturing, sourcing and distribution under one team','check',20,1,NOW(3),NOW(3)),
('Flexible OEM and ODM customization','check',30,1,NOW(3),NOW(3)),
('Technical assistance and product design','check',40,1,NOW(3),NOW(3)),
('Reliable on-time delivery','check',50,1,NOW(3),NOW(3)),
('Stock available for standard specifications','check',60,1,NOW(3),NOW(3)),
('Split and consolidated shipment support','check',70,1,NOW(3),NOW(3)),
('Complete product line for fluid systems','check',80,1,NOW(3),NOW(3)),
('ISO 9001 certified quality management','check',90,1,NOW(3),NOW(3)),
('NSF and UPC certified product options','check',100,1,NOW(3),NOW(3)),
('China and Taiwan manufacturing bases','check',110,1,NOW(3),NOW(3)),
('High-precision CNC and multi-axis machinery','check',120,1,NOW(3),NOW(3));

INSERT INTO `product_categories` (`id`,`parent_id`,`name`,`slug`,`image_url`,`summary`,`home_featured`,`sort`,`status`,`created_at`,`updated_at`) VALUES
(1,0,'Brass Fittings','brass-fittings','https://www.hbfittings.net/Content/uploads/2021806904/202106180949279a1309ce467e47a5ab7bc552fff7b95f.jpg','Brass pipe, hose barb, compression, push-fit, garden and hydraulic connection solutions.',1,10,1,NOW(3),NOW(3)),
(2,0,'Brass Instrument Valve','brass-instrument-valve','https://www.hbfittings.net/uploads/33800/small/en331-approved-nickel-plated-brass-gas-ball52bba.png','Needle, ball, check, drain, safety and specialty brass valves.',0,20,1,NOW(3),NOW(3)),
(3,0,'Pressure Gauge Accessories','pressure-gauge-accessories','https://www.hbfittings.net/Content/uploads/2021806904/20210618094714fc7ea8c7bc62444280951f16881dd15d.jpg','Gauge cocks, test plugs, pressure snubbers, adapters and syphon tubes.',1,30,1,NOW(3),NOW(3)),
(4,0,'Stainless Steel Valve','stainless-steel-valve','https://www.hbfittings.net/uploads/33800/small/forged-316-stainless-steel-pipe-fittings532bc.png','Instrumentation needle valves and safety valves for demanding media.',0,40,1,NOW(3),NOW(3)),
(5,0,'Stainless Steel Ball Valve','stainless-steel-ball-valve','https://www.hbfittings.net/uploads/33800/small/high-quality-high-pressure-elbow-forged-pipe61906.png','High-performance threaded and welded stainless steel ball valves.',0,50,1,NOW(3),NOW(3)),
(6,0,'Stainless Steel Fitting','stainless-steel-fitting','https://www.hbfittings.net/uploads/33800/small/stainless-steel-threaded-eccentric-couplingc403d.png','Compression tube fittings and quick connectors in 304 and 316 stainless steel.',0,60,1,NOW(3),NOW(3)),
(7,0,'Hydraulic Fittings','hydraulic-fittings','https://www.hbfittings.net/uploads/33800/small/hydraulic-hose-reusable-fitting1e824.png','BSP, JIC and reusable hydraulic hose fittings for industrial equipment.',0,70,1,NOW(3),NOW(3)),
(8,0,'Forged Pipe Fittings','forged-pipe-fittings','https://www.hbfittings.net/uploads/33800/small/thread-and-socket-welding-pipe-union0869b.png','High-pressure forged elbows, tees, couplings and unions.',0,80,1,NOW(3),NOW(3)),
(9,0,'Auto Parts Fittings','auto-parts-fittings','https://www.hbfittings.net/uploads/33800/small/high-pressure-stainless-steel-pipe-nipple645f7.png','Oxygen sensor fittings, adapters, bungs and specialty automotive components.',0,90,1,NOW(3),NOW(3)),
(10,0,'Reusable Hose Fittings','reusable-hose-fittings','https://www.hbfittings.net/uploads/202633800/small/male-pipe-reusable-hydraulic-hose-fittingc946c90e-98c8-4db7-9ad6-c3bfe40d195f.webp','Field-installable reusable hose fittings for maintenance and repair.',0,100,1,NOW(3),NOW(3)),
(101,1,'Brass Pipe Fittings','brass-pipe-fittings','https://www.hbfittings.net/Content/uploads/2021806904/2021061809482191882e6e776d427097002d6e5c760602.jpg','NPT and BSP nipples, elbows, tees, adapters and couplings.',1,5,1,NOW(3),NOW(3)),
(102,1,'Brass Hose Barb Fittings','brass-hose-barb-fittings','https://www.hbfittings.net/Content/uploads/2021806904/202106180949279a1309ce467e47a5ab7bc552fff7b95f.jpg','Secure hose connections for water, air, fuel and industrial media.',0,20,1,NOW(3),NOW(3)),
(103,1,'Brass Compression Fitting','brass-compression-fitting','https://www.hbfittings.net/Content/uploads/2021806904/202106180949279a1309ce467e47a5ab7bc552fff7b95f.jpg','Reliable compression connections for copper and plastic tubing.',0,30,1,NOW(3),NOW(3)),
(104,1,'Garden Hose Fitting','garden-hose-fitting','https://www.hbfittings.net/uploads/33800/news/n202607291544016baf6.jpg','Standard and custom garden hose adapters and couplings.',0,40,1,NOW(3),NOW(3)),
(201,2,'Brass Ball Valve','brass-ball-valve','https://www.hbfittings.net/uploads/33800/small/600-psi-wog-brass-gas-ball-valve-for-gas39c47.png','Compact and full-port brass ball valves for gas and liquid systems.',0,10,1,NOW(3),NOW(3)),
(301,3,'Pressure Syphon Tube','pressure-syphon-tube','https://www.hbfittings.net/Content/uploads/2021806904/20210618094714fc7ea8c7bc62444280951f16881dd15d.jpg','Coil and pigtail syphon tubes for pressure instrument protection.',0,10,1,NOW(3),NOW(3)),
(601,6,'Compression Tube Fittings','compression-tube-fittings','https://www.hbfittings.net/uploads/33800/small/stainless-steel-threaded-eccentric-couplingc403d.png','Double ferrule tube fittings for high-pressure instrumentation.',0,10,1,NOW(3),NOW(3)),
(701,7,'BSP Standards','bsp-hydraulic-fittings','https://www.hbfittings.net/uploads/33800/small/hydraulic-hose-reusable-fitting1e824.png','BSPP and BSPT hydraulic adapters and hose connections.',0,10,1,NOW(3),NOW(3)),
(702,7,'JIC Standards','jic-hydraulic-fittings','https://www.hbfittings.net/uploads/202633800/small/jic-37-swivel-reusable-hydraulic-hose-fitting1eabf2ce-ba27-4461-a832-ae51e521651e.webp','JIC 37-degree flare hydraulic fittings and adapters.',0,20,1,NOW(3),NOW(3));

INSERT INTO `products` (`id`,`category_id`,`name`,`slug`,`sku`,`summary`,`description`,`main_image`,`video_url`,`material`,`size`,`thread_standard`,`pressure_rating`,`temperature_range`,`moq`,`standard`,`application`,`hot_tags`,`featured`,`latest`,`sort`,`status`,`created_at`,`updated_at`) VALUES
(1,201,'EN331 Approved Nickel Plated Brass Gas Ball Valve','en331-approved-nickel-plated-brass-gas-ball-valve','DP-BV-331','Nickel-plated brass gas ball valve with nozzle and female connection, available for OEM sizing.','<h2>Production Introduction</h2><p>This compact gas ball valve combines a forged brass body, smooth quarter-turn operation and leak-resistant sealing for gas piping systems.</p><h3>Products Feature</h3><ul><li>100% pressure tested before shipment</li><li>Custom thread, handle and logo options</li><li>EN331 configuration available</li></ul><h3>Why Choose Us</h3><p>Depo provides CNC machining, traceable inspection and engineering support from sample to volume production.</p>','https://www.hbfittings.net/uploads/33800/small/en331-approved-nickel-plated-brass-gas-ball52bba.png','','Forged brass, nickel plated','1/4-1/2 in','BSPP / BSPT / NPT','600 PSI WOG','-20 C to 120 C','500 pcs','EN331','Natural gas and LPG piping','brass gas ball valve,EN331 valve,nickel plated valve',1,1,10,1,NOW(3),NOW(3)),
(2,201,'Female x Flare Angle Brass Gas Ball Valve With T Handle','female-flare-angle-brass-gas-ball-valve','DP-BV-A38','Angle-pattern brass gas valve with female inlet, flare outlet and compact T handle.','<h2>Production Introduction</h2><p>Designed for tight installations where a 90-degree change of direction is required. Threads and flare sizes can be customized.</p><h3>Quality Control</h3><p>Every valve receives dimensional, surface and leak testing before packing.</p>','https://www.hbfittings.net/uploads/33800/small/1-2-fip-x-3-8-flare-angle-brass-gas-ballff2b5.png','','Brass','1/4-1 in','Female x SAE flare','600 PSI','-20 C to 120 C','500 pcs','ANSI / OEM','Gas appliance connection','angle gas valve,flare ball valve,T handle valve',1,1,20,1,NOW(3),NOW(3)),
(3,201,'600 PSI WOG Brass Female Gas Ball Valve','600-psi-wog-brass-female-gas-ball-valve','DP-BV-600F','Two-piece female brass ball valve for gas piping systems and industrial service.','<h2>Product Overview</h2><p>A full-flow two-piece construction provides low pressure drop and dependable shutoff. Available with BSPP, BSPT or NPT threads.</p><h3>Customization</h3><p>Body marking, handle color, package and size are available to order.</p>','https://www.hbfittings.net/uploads/33800/small/600-psi-wog-brass-gas-ball-valve-for-gas39c47.png','','Forged brass','1/4-1 in','Female x Female BSP / NPT','600 PSI WOG','-20 C to 120 C','500 pcs','OEM','Gas and water pipeline','600 PSI ball valve,brass valve,female valve',1,1,30,1,NOW(3),NOW(3)),
(4,201,'Brass Flare x Flare Gas Ball Valve','brass-flare-flare-gas-ball-valve','DP-BV-FF','Compact inline flare ball valve manufactured for OEM and ODM gas equipment programs.','<h2>Product Details</h2><p>Precision flare seats support quick assembly and dependable sealing without thread sealant.</p><h3>Applications</h3><p>Suitable for gas appliances, HVAC equipment and instrument utility lines.</p>','https://www.hbfittings.net/uploads/33800/small/brass-flare-x-flare-gas-ball-valve-oem-odm44b23.png','','Brass','1/4-1 in','SAE flare x flare','600 PSI','-20 C to 120 C','500 pcs','SAE / OEM','Gas, HVAC and instrumentation','flare valve,OEM brass valve,gas fitting',1,1,40,1,NOW(3),NOW(3)),
(5,201,'Male Thread Brass Gas Valve With Butterfly Handle','male-thread-brass-gas-valve-butterfly-handle','DP-BV-MF','Compact male-to-flare brass gas valve with a low-profile butterfly handle.','<h2>Production Introduction</h2><p>The compact handle and forged body make this valve ideal for confined gas appliance connections.</p><h3>Options</h3><p>Custom plating, laser logo, thread and packaging are supported.</p>','https://www.hbfittings.net/uploads/33800/small/brass-gas-flare-ball-valve-male-thread-brassd752f.png','','Forged brass','1/4-1 in','Male thread x flare','600 PSI','-20 C to 120 C','500 pcs','OEM','Gas appliance and utility connection','butterfly handle valve,male gas valve,brass valve',1,1,50,1,NOW(3),NOW(3)),
(6,701,'Hydraulic Hose Reusable Fitting','hydraulic-hose-reusable-fitting','DP-HY-RF','Field-installable reusable hydraulic hose fitting for maintenance and emergency repair.','<h2>Reusable Hydraulic Fitting</h2><p>This fitting can be assembled without a crimping machine and is available in carbon steel, stainless steel and brass.</p><h3>Features</h3><ul><li>Fast field installation</li><li>Multiple thread standards</li><li>Corrosion-resistant finishes</li></ul>','https://www.hbfittings.net/uploads/33800/small/hydraulic-hose-reusable-fitting1e824.png','','Carbon steel / stainless steel / brass','1/4-1 in','BSP / NPT','Up to 5000 PSI','-40 C to 120 C','100 pcs','ISO / SAE','Hydraulic hose repair','reusable fitting,hydraulic hose fitting,BSP fitting',1,1,60,1,NOW(3),NOW(3)),
(7,701,'Male Pipe Reusable Hydraulic Hose Fitting','male-pipe-reusable-hydraulic-hose-fitting','DP-HY-MP','Straight male pipe reusable fitting for single-wire hydraulic hose assemblies.','<h2>Product Overview</h2><p>Machined threads and a robust socket provide a secure reusable connection for field service.</p><h3>Inspection</h3><p>Thread gauges and dimensional controls are applied throughout production.</p>','https://www.hbfittings.net/uploads/202633800/small/male-pipe-reusable-hydraulic-hose-fittingc946c90e-98c8-4db7-9ad6-c3bfe40d195f.webp','','Carbon steel','1/4-1 in','NPT / BSPT male','Up to 5000 PSI','-40 C to 120 C','100 pcs','SAE / ISO','Mobile and industrial hydraulics','male pipe fitting,reusable hose fitting,hydraulic adapter',1,1,70,1,NOW(3),NOW(3)),
(8,702,'JIC 37 Swivel Reusable Hydraulic Hose Fitting','jic-37-swivel-reusable-hydraulic-hose-fitting','DP-HY-JIC37','JIC 37-degree female swivel reusable fitting for convenient hose routing and maintenance.','<h2>Product Details</h2><p>The swivel nut supports convenient installation while the 37-degree cone provides a reliable metal-to-metal seal.</p><h3>Material Options</h3><p>Carbon steel and stainless steel versions are available.</p>','https://www.hbfittings.net/uploads/202633800/small/jic-37-swivel-reusable-hydraulic-hose-fitting1eabf2ce-ba27-4461-a832-ae51e521651e.webp','','Carbon steel / stainless steel','1/4-1 in','JIC 37 female swivel','Up to 5000 PSI','-40 C to 120 C','100 pcs','SAE J514','Hydraulic hose assembly','JIC 37 fitting,swivel fitting,reusable hose fitting',1,1,80,1,NOW(3),NOW(3)),
(9,8,'High Pressure Forged Stainless Steel Elbow','high-pressure-forged-stainless-steel-elbow','DP-FG-EL90','Forged 90-degree elbow for high-pressure threaded and socket-weld piping.','<h2>Forged Pipe Fitting</h2><p>Manufactured from forged stainless steel for compact, high-strength pressure connections.</p><h3>Standards</h3><p>Dimensional and material configurations are available to ASME B16.11 and customer drawings.</p>','https://www.hbfittings.net/uploads/33800/small/high-quality-high-pressure-elbow-forged-pipe61906.png','','Stainless steel 304 / 316','1/8-4 in','NPT / BSP / socket weld','Class 3000 / 6000 / 9000','-196 C to 400 C','50 pcs','ASME B16.11','Oil, gas, chemical and power','forged elbow,high pressure fitting,stainless steel elbow',1,1,90,1,NOW(3),NOW(3)),
(10,8,'Forged 316 Stainless Steel Pipe Fitting','forged-316-stainless-steel-pipe-fitting','DP-FG-316','Corrosion-resistant forged 316 stainless steel fitting for chemical and offshore service.','<h2>Production Introduction</h2><p>Forged construction and controlled machining provide strength, dimensional consistency and corrosion resistance.</p><h3>Testing</h3><p>Material verification and dimensional inspection are available for critical projects.</p>','https://www.hbfittings.net/uploads/33800/small/forged-316-stainless-steel-pipe-fittings532bc.png','','316 / 316L stainless steel','1/8-4 in','NPT / socket weld','Class 3000 / 6000','-196 C to 400 C','50 pcs','ASME B16.11','Chemical, marine and offshore','316 fitting,forged pipe fitting,chemical fitting',1,1,100,1,NOW(3),NOW(3)),
(11,8,'High Pressure Stainless Steel Pipe Nipple','high-pressure-stainless-steel-pipe-nipple','DP-SS-NP','Precision-machined stainless steel pipe nipple for high-pressure threaded systems.','<h2>Stainless Steel Pipe Nipple</h2><p>Available in close, hex and extended configurations with NPT, BSPT or customer-specific threads.</p><h3>OEM Service</h3><p>Length, material, thread and surface finish can be produced to drawing.</p>','https://www.hbfittings.net/uploads/33800/small/high-pressure-stainless-steel-pipe-nipple645f7.png','','304 / 316 stainless steel','1/8-4 in','NPT / BSPT','Up to 6000 PSI','-196 C to 400 C','100 pcs','ASME / OEM','Process piping and instrumentation','pipe nipple,stainless steel nipple,high pressure fitting',1,1,110,1,NOW(3),NOW(3)),
(12,601,'Stainless Steel Compression Union Tee','stainless-steel-compression-union-tee','DP-CT-UT','Double-ferrule union tee for leak-tight tube branching in instrumentation systems.','<h2>Production Introduction</h2><p>The Depo compression union tee connects three equal-size tubes using a two-ferrule design that supports repeatable, leak-tight assembly.</p><p><img src="https://www.hbfittings.net/uploads/33800/small/stainless-steel-threaded-eccentric-couplingc403d.png" alt="compression fitting"></p><h3>Products Feature</h3><ul><li>316 stainless steel construction</li><li>Precision-machined ferrules and body</li><li>Compatible with common fractional and metric tubing</li></ul><h3>Why Choose Us</h3><p>Full CNC production, material traceability and 100% outgoing inspection support demanding industrial projects.</p>','https://www.hbfittings.net/uploads/33800/small/stainless-steel-threaded-eccentric-couplingc403d.png','', '316 stainless steel','1/8-1 in, 3-25 mm','Double ferrule tube connection','Up to 6000 PSI','-196 C to 400 C','50 pcs','ASTM / OEM','Instrumentation, hydrogen and laboratory','compression union tee,double ferrule fitting,316 tube fitting',1,1,120,1,NOW(3),NOW(3));

INSERT INTO `product_images` (`product_id`,`image_url`,`alt_text`,`sort`,`status`,`created_at`,`updated_at`) VALUES
(1,'https://www.hbfittings.net/uploads/33800/small/en331-approved-nickel-plated-brass-gas-ball52bba.png','EN331 nickel plated brass gas ball valve',10,1,NOW(3),NOW(3)),
(1,'https://www.hbfittings.net/Content/uploads/2021806904/202106180949279a1309ce467e47a5ab7bc552fff7b95f.jpg','Brass fitting production range',20,1,NOW(3),NOW(3)),
(6,'https://www.hbfittings.net/uploads/33800/small/hydraulic-hose-reusable-fitting1e824.png','Reusable hydraulic hose fitting',10,1,NOW(3),NOW(3)),
(6,'https://www.hbfittings.net/uploads/202633800/small/male-pipe-reusable-hydraulic-hose-fittingc946c90e-98c8-4db7-9ad6-c3bfe40d195f.webp','Male pipe reusable fitting',20,1,NOW(3),NOW(3)),
(9,'https://www.hbfittings.net/uploads/33800/small/high-quality-high-pressure-elbow-forged-pipe61906.png','Forged stainless steel elbow',10,1,NOW(3),NOW(3)),
(9,'https://www.hbfittings.net/uploads/33800/small/forged-316-stainless-steel-pipe-fittings532bc.png','Forged stainless steel fitting family',20,1,NOW(3),NOW(3)),
(12,'https://www.hbfittings.net/uploads/33800/small/stainless-steel-threaded-eccentric-couplingc403d.png','Stainless steel compression union tee',10,1,NOW(3),NOW(3)),
(12,'https://www.hbfittings.net/uploads/33800/small/thread-half-couplingd90a1.png','Stainless steel tube fitting detail',20,1,NOW(3),NOW(3));

INSERT INTO `content_pages` (`id`,`title`,`slug`,`subtitle`,`content`,`cover_image`,`template`,`sort`,`status`,`created_at`,`updated_at`) VALUES
(1,'About Us','about-us','Professional brass and stainless steel valve and fitting manufacturer since 2007.','<p>Hubei Depo Valve and Fitting Co., Ltd. is a professional manufacturer of brass and stainless steel valves and fittings in China. Our headquarters, Wenzhou Hi-Tek Valve & Fitting Co., Ltd., was founded in 2007.</p><h2>Integrated Manufacturing Capability</h2><p>We operate brass and stainless steel production resources in mainland China and Taiwan. Full CNC machining, automated production lines and advanced testing equipment support product development, manufacturing, sales and after-sales service.</p><h2>Materials and Markets</h2><p>Available materials include CA360, CA345, CA377, DZR brass, lead-free brass C46500, stainless steel 304 and 316, duplex steel, Monel and aluminum. Our products serve oil and gas, pharmaceutical, food and beverage, chemical, water treatment, HVAC, automotive and industrial automation markets.</p><h2>Quality Control & Test Equipment</h2><p>Quality is the lifeblood of every Depo product. Our production team follows controlled inspection procedures from incoming material to final shipment, with training, calibrated gauges, pressure testing and complete outgoing inspection.</p><h2>Mission & Vision</h2><p>Our mission is to make global fluid connections safer, simpler and more dependable. Our vision is to build lasting customer partnerships through engineering support, honest communication and consistent quality.</p>','https://www.hbfittings.net/uploads/33800/index/3.jpg','about',10,1,NOW(3),NOW(3)),
(2,'Company Profile','company-profile','A family-owned manufacturer serving global industrial customers.','<p>Depo brings together product development, machining, assembly, inspection, export service and after-sales support. Our team works with distributors, equipment manufacturers and project contractors throughout North America, Europe and other developed markets.</p><h2>Our Capabilities</h2><ul><li>Full CNC and multi-axis machining</li><li>Automated production and controlled assembly</li><li>Pressure, sealing and dimensional inspection</li><li>Material, thread, logo and packaging customization</li><li>Consolidated shipment and global logistics support</li></ul>','https://www.hbfittings.net/uploads/33800/index/2.jpg','standard',20,1,NOW(3),NOW(3)),
(3,'OEM','oem','From a drawing or sample to dependable volume production.','<p>Our OEM and ODM process covers requirement review, material recommendation, design-for-manufacturing feedback, sampling, validation and controlled production.</p><h2>What We Can Customize</h2><p>Material, size, thread, pressure rating, surface treatment, laser logo, handle color, individual packaging and carton artwork can be tailored to your market.</p><h2>Start Your Project</h2><p>Send a drawing, sample photo, BOM or target standard. Our engineers will review feasibility and provide a practical production proposal.</p>','https://www.hbfittings.net/uploads/33800/index/4.jpg','standard',30,1,NOW(3),NOW(3)),
(4,'Materials','materials','Material choices matched to pressure, media, temperature and compliance needs.','<h2>Brass</h2><p>CA360, CA345, CA377, DZR grades CW602N and CW617N, and lead-free C46500 are available for plumbing, gas and industrial applications.</p><h2>Stainless Steel and Special Alloys</h2><p>304, 316 and 316L stainless steel are standard options. Duplex steel, super duplex, Monel, carbon steel and aluminum can be evaluated for special projects.</p><h2>Material Control</h2><p>Certificates, traceability and third-party testing can be arranged according to the order and applicable specification.</p>','https://www.hbfittings.net/uploads/33800/index/5.jpg','standard',40,1,NOW(3),NOW(3)),
(5,'Service','service','Responsive support before, during and after production.','<h2>Engineering Support</h2><p>Our team assists with product selection, thread and material compatibility, custom design review and sample development.</p><h2>Order Execution</h2><p>Clear milestones, production updates, outgoing inspection and flexible shipping options keep international orders predictable.</p><h2>After-Sales</h2><p>We respond quickly to technical questions and provide corrective support whenever a delivered product requires investigation.</p>','https://www.hbfittings.net/uploads/33800/index/6.jpg','standard',50,1,NOW(3),NOW(3)),
(6,'FAQ','faq','Common questions from international buyers.','<h2>What is your minimum order quantity?</h2><p>MOQ depends on the product and customization. Standard items may start from 50 to 500 pieces.</p><h2>Can you manufacture from a drawing or sample?</h2><p>Yes. OEM and ODM development is a core service. Please send dimensions, material, quantity and operating requirements.</p><h2>Which certifications are available?</h2><p>Depo maintains ISO quality management and offers selected NSF, UPC, lead-free and market-specific certified products.</p><h2>How quickly do you reply?</h2><p>Our sales and engineering team normally responds within 24 hours.</p>','https://www.hbfittings.net/uploads/33800/index/7.jpg','standard',60,1,NOW(3),NOW(3)),
(7,'Privacy Policy','privacy-policy','How we handle website and inquiry information.','<p>We collect only the contact and project information needed to answer inquiries, prepare quotations, provide technical recommendations and improve customer service.</p><p>We do not sell personal information. Submitted drawings and project details are treated as confidential business information and are shared only with team members who need them to support the request.</p><p>Contact summer@hbfittings.net to request access, correction or deletion of submitted personal information.</p>','https://www.hbfittings.net/uploads/33800/index/8.jpg','policy',70,1,NOW(3),NOW(3));

INSERT INTO `team_members` (`name`,`role`,`email`,`image_url`,`bio`,`sort`,`status`,`created_at`,`updated_at`) VALUES
('Summer Huang','Overseas Sales Manager','summer@hbfittings.net','https://www.hbfittings.net/Content/uploads/2026806904/202603301732314480f02aaac042c7b97541f1aa97567a.jpg','International project coordination and customer solutions.',10,1,NOW(3),NOW(3)),
('Vicky Lee','Sales','vicky01@hbfittings.net','https://www.hbfittings.net/Content/uploads/2026806904/20260330173231dc0d7e97056e4479822f1ebbf4b9555f.jpg','Product sourcing and customer order support.',20,1,NOW(3),NOW(3)),
('Linda Chen','Sales','sales02@hbfittings.net','https://www.hbfittings.net/Content/uploads/2026806904/20260330173231a8015acc8d654c41bb90aea0cad65ea4.jpg','Quotation, sampling and export order service.',30,1,NOW(3),NOW(3)),
('Jack Ji','Technical Engineer','jack@hbfittings.net','https://www.hbfittings.net/Content/uploads/2026806904/2026033017323173656bf663ea48ebb3f74a461d9e6f97.jpg','Application review, product development and technical support.',40,1,NOW(3),NOW(3)),
('James Liu','General Manager','admin@hbfittings.net','https://www.hbfittings.net/Content/uploads/2026806904/202603301732305e9cc45c79414ed5bdc3c3f65b6e331f.jpg','Manufacturing strategy, quality and long-term partnerships.',50,1,NOW(3),NOW(3));

INSERT INTO `partners` (`name`,`logo_url`,`website_url`,`sort`,`status`,`created_at`,`updated_at`) VALUES
('Partner 01','https://www.hbfittings.net/Content/uploads/2022806904/20221020114824b2aa871a3879462481857eeb5e51e7ff.jpg','',10,1,NOW(3),NOW(3)),
('Partner 02','https://www.hbfittings.net/Content/uploads/2022806904/20221020114832f96fc14b682b4ea98b8b2cc6c37c9df7.jpg','',20,1,NOW(3),NOW(3)),
('Partner 03','https://www.hbfittings.net/Content/uploads/2022806904/20221020114838021991d5b0144d39918c79a8a942b3bf.jpg','',30,1,NOW(3),NOW(3)),
('Partner 04','https://www.hbfittings.net/Content/uploads/2022806904/202210201150188d8ce25e20bd4794af3f5402f5703926.jpg','',40,1,NOW(3),NOW(3)),
('Partner 05','https://www.hbfittings.net/Content/uploads/2022806904/2022102011502716076bac6bc44a338c321a0ea19c8a10.jpg','',50,1,NOW(3),NOW(3)),
('Partner 06','https://www.hbfittings.net/Content/uploads/2022806904/2022102011512915e1f7c1f5e64f81ad6abcb2d02b7e8b.jpg','',60,1,NOW(3),NOW(3)),
('Partner 07','https://www.hbfittings.net/Content/uploads/2022806904/20221020115137c83bc62dbf8b43daa0138c91947719d2.jpg','',70,1,NOW(3),NOW(3)),
('Partner 08','https://www.hbfittings.net/Content/uploads/2022806904/2022102011520804c3cb780b1b47a096c1f0c72d2071ae.jpg','',80,1,NOW(3),NOW(3)),
('Partner 09','https://www.hbfittings.net/Content/uploads/2022806904/20221020115510b4a1f0329ef746a3a3a80af3e2b1fd52.jpg','',90,1,NOW(3),NOW(3)),
('Partner 10','https://www.hbfittings.net/Content/uploads/2022806904/202210201155202b1e8b7294f241378e503b1e7eb1efed.jpg','',100,1,NOW(3),NOW(3)),
('Partner 11','https://www.hbfittings.net/Content/uploads/2022806904/202210201155286a83ca9e0adc432d95c6251f5d727096.jpg','',110,1,NOW(3),NOW(3));

INSERT INTO `industries` (`title`,`subtitle`,`description`,`image_url`,`link_url`,`sort`,`status`,`created_at`,`updated_at`) VALUES
('Pharmaceutical & Food','Protecting purity from process to product','Depo provides corrosion-resistant, cleanable fluid components for pharmaceutical, biotechnology, food and beverage systems. Reliable sealing and carefully controlled materials help minimize contamination risk and support stable production.','https://www.hbfittings.net/uploads/33800/index/1.jpg','/products',10,1,NOW(3),NOW(3)),
('Hydrogen Energy','Develop hydrogen energy for a greener future','Hydrogen storage, transport and refueling equipment requires strict pressure resistance and sealing. Depo supplies high-performance fittings and valves tailored to demanding hydrogen service.','https://www.hbfittings.net/uploads/33800/index/2.jpg','/products',20,1,NOW(3),NOW(3)),
('Petroleum & Petrochemical','Advancing energy exploration and production','Our tube fittings, instrument valves and related components serve measurement, calibration, sampling and process control systems throughout petroleum and petrochemical facilities.','https://www.hbfittings.net/uploads/33800/index/3.jpg','/products',30,1,NOW(3),NOW(3)),
('Refinery & Chemical','Safe, leak-free fluid systems','Professional fluid solutions support fixed plants, offshore platforms, natural gas processing, transmission, storage and other demanding refinery and chemical operations.','https://www.hbfittings.net/uploads/33800/index/4.jpg','/products',40,1,NOW(3),NOW(3)),
('CNG & LNG','Safety-centered solutions for natural gas systems','High-pressure, corrosion-resistant tube fittings and control valves are designed to maintain sealing performance and long-term stability in CNG and LNG service.','https://www.hbfittings.net/uploads/33800/index/5.jpg','/products',50,1,NOW(3),NOW(3)),
('Laboratory','Accuracy begins with stable fluid control','Precision fittings and valves support spectrometers, chromatographs, liquid analyzers and other laboratory instruments that depend on consistent flow and leak-tight connections.','https://www.hbfittings.net/uploads/33800/index/6.jpg','/products',60,1,NOW(3),NOW(3)),
('Solar Energy & Semiconductor','Driving progress with renewable energy','High-purity components and custom fluid solutions support reliable production and auxiliary systems in photovoltaic and semiconductor manufacturing.','https://www.hbfittings.net/uploads/33800/index/7.jpg','/products',70,1,NOW(3),NOW(3)),
('HVAC System','Comfortable and reliable climate control','Brass fittings, test plugs, syphon tubes, needle valves and control components provide dependable sealing and straightforward installation for HVAC and refrigeration systems.','https://www.hbfittings.net/uploads/33800/index/8.jpg','/products',80,1,NOW(3),NOW(3)),
('Thermal & Nuclear Power','Components for critical power systems','A diverse fitting and valve range supports steam-water, power generation, instrument and control systems where safety, documentation and operating reliability are essential.','https://www.hbfittings.net/uploads/33800/index/9.jpg','/products',90,1,NOW(3),NOW(3));

INSERT INTO `content_articles` (`content_type`,`category`,`title`,`slug`,`summary`,`content`,`cover_image`,`published_at`,`featured`,`sort`,`status`,`created_at`,`updated_at`) VALUES
('news','Customer feedback','Custom Aluminum Garden Hose Fittings Delivered to the USA','custom-aluminum-garden-hose-fittings-usa','A custom material recommendation helped a U.S. customer control cost while achieving the requested silver finish.','<h2>From Rising Brass Prices to a Better Solution</h2><p>A U.S. customer required 2,000 custom garden hose fittings but needed an alternative to rising brass costs and preferred a silver appearance. Our engineering team evaluated the application and recommended a customized aluminum fitting.</p><h2>Fast Engineering and Flexible Production</h2><p>We reviewed the requirements, optimized the design, prepared samples and arranged production around the customer timeline. Free laser marking and tailored packaging were included.</p><h2>A Long-Term Result</h2><p>The customer confirmed satisfaction with product quality, communication and delivery, and plans to continue cooperation on larger projects.</p>','https://www.hbfittings.net/uploads/33800/news/n202607291544016baf6.jpg','2026-07-29 15:44:00',1,10,1,NOW(3),NOW(3)),
('news','Customer orders case','2,000 Compression Fittings Delivered to Kazakhstan in 10 Days','compression-fittings-delivered-kazakhstan','A coordinated production and land-transport plan moved 2,000 stainless steel compression fittings to Kazakhstan in ten days.','<h2>Project Requirement</h2><p>The customer required a fast delivery of stainless steel compression fittings with clear dimensional inspection and export packing.</p><h2>Execution</h2><p>Available material and production capacity were coordinated immediately. Inspection, labeling and consolidated land transport kept the project on schedule.</p><h2>Outcome</h2><p>The fittings arrived within the requested ten-day window and the customer approved the order for future repeat business.</p>','https://www.hbfittings.net/uploads/202133800/n202108121437007083268.jpg','2026-07-15 09:30:00',1,20,1,NOW(3),NOW(3)),
('news','shipment news','Lead-Free Brass Mini Ball Valve Shipment to USA','lead-free-brass-mini-ball-valve-shipment-usa','Lead-free C46500 mini ball valves completed inspection and export packing for a U.S. plumbing customer.','<h2>Product and Material</h2><p>The order used lead-free C46500 brass with custom dimensions and packaging for the U.S. plumbing market.</p><h2>Inspection</h2><p>Thread gauges, dimensional checks and leak tests were completed before individual protection and carton packing.</p>','https://www.hbfittings.net/uploads/33800/news/n20260509222859fe628.jpg','2026-05-09 22:28:00',1,30,1,NOW(3),NOW(3)),
('news','Company culture','Meet Our Overseas Sales Manager Summer','meet-sales-manager-summer','Professional service is built by people who understand both product details and international customer expectations.','<h2>Customer-Focused Communication</h2><p>Summer coordinates quotations, technical reviews, production milestones and shipping details for international projects.</p><p>Her approach combines fast response with careful requirement confirmation so customers receive practical solutions instead of generic answers.</p>','https://www.hbfittings.net/uploads/202633800/nad9e6aae-6639-4aef-827b-8ddff9bd5c8c.jpg','2026-04-14 10:00:00',1,40,1,NOW(3),NOW(3)),
('knowledge','brass valve','How Does a Brass Male-to-Female Needle Valve Work?','how-brass-male-female-needle-valve-works','A practical explanation of the stem, needle and seat used to regulate flow accurately.','<h2>Operating Principle</h2><p>Turning the handle moves a finely tapered needle toward or away from the valve seat. The small, controlled change in opening provides much more precise throttling than a ball valve.</p><h2>Selection Points</h2><p>Confirm thread type, material compatibility, pressure, temperature and whether the application requires panel mounting or a lockable handle.</p>','https://www.hbfittings.net/Content/uploads/2021806904/20210618094714fc7ea8c7bc62444280951f16881dd15d.jpg','2026-03-28 08:30:00',0,10,1,NOW(3),NOW(3)),
('knowledge','material','Choosing Brass, DZR Brass or Stainless Steel','choosing-brass-dzr-stainless-steel','Compare common fitting materials based on media, corrosion, temperature, regulations and lifecycle cost.','<h2>Standard Brass</h2><p>Machinable brass is cost-effective for many air, water and general industrial connections.</p><h2>DZR and Lead-Free Brass</h2><p>DZR grades improve resistance in aggressive water conditions, while lead-free grades support regulated potable-water markets.</p><h2>Stainless Steel</h2><p>304 and 316 stainless steel provide higher temperature capability, strength and corrosion resistance for chemical, marine and instrumentation service.</p>','https://www.hbfittings.net/uploads/33800/index/7.jpg','2026-03-12 08:30:00',0,20,1,NOW(3),NOW(3)),
('knowledge','hydraulic fittings','Understanding BSP and JIC Hydraulic Connections','understanding-bsp-jic-hydraulic-connections','How BSPP, BSPT and JIC 37-degree connections seal and where each standard is commonly used.','<h2>BSPP and BSPT</h2><p>BSPP threads are parallel and typically seal with a bonded washer or cone. BSPT threads are tapered and seal on the thread with an appropriate sealant.</p><h2>JIC 37 Degree</h2><p>JIC fittings use a 37-degree metal flare and are widely used in mobile and industrial hydraulic systems.</p>','https://www.hbfittings.net/uploads/202633800/small/jic-37-swivel-reusable-hydraulic-hose-fitting1eabf2ce-ba27-4461-a832-ae51e521651e.webp','2026-02-21 08:30:00',0,30,1,NOW(3),NOW(3)),
('blog','Product Guide','What Pressure Rating Should a Brass Fitting Have?','pressure-rating-brass-fitting','Pressure rating depends on alloy, geometry, size, temperature, connection type and the governing standard.','<h2>There Is No Single Universal Rating</h2><p>Two fittings made from the same brass may have different ratings because wall thickness, shape and thread design change stress distribution.</p><h2>Ask the Right Questions</h2><p>Confirm maximum working and surge pressure, temperature, media, cycle frequency, applicable standard and safety factor before selection.</p>','https://www.hbfittings.net/Content/uploads/2021806904/2021061809482191882e6e776d427097002d6e5c760602.jpg','2026-01-30 08:30:00',0,10,1,NOW(3),NOW(3)),
('blog','Engineering','Seven Details to Include in an OEM Fitting Drawing','details-oem-fitting-drawing','A complete drawing reduces sampling time and prevents assumptions about threads, tolerances and sealing surfaces.','<h2>Essential Drawing Details</h2><ol><li>Material and material standard</li><li>Complete dimensions and tolerances</li><li>Thread designation and gauge standard</li><li>Sealing surfaces</li><li>Pressure and temperature</li><li>Surface finish or plating</li><li>Marking and packaging</li></ol><p>A physical sample and application information are also valuable when a legacy drawing is incomplete.</p>','https://www.hbfittings.net/uploads/33800/index/2.jpg','2026-01-16 08:30:00',0,20,1,NOW(3),NOW(3)),
('blog','Maintenance','How to Avoid Leaks in Compression Tube Fittings','avoid-leaks-compression-tube-fittings','Correct tube preparation, insertion and make-up are essential for repeatable double-ferrule fitting performance.','<h2>Prepare the Tube</h2><p>Cut the tube square, remove burrs and confirm the outside surface is free from deep scratches.</p><h2>Assemble Correctly</h2><p>Insert the tube fully against the shoulder, follow the specified nut rotation and avoid mixing components from incompatible systems.</p><h2>Inspect the System</h2><p>Support tubing against vibration and complete a controlled leak test before operation.</p>','https://www.hbfittings.net/uploads/33800/small/stainless-steel-threaded-eccentric-couplingc403d.png','2025-12-18 08:30:00',0,30,1,NOW(3),NOW(3)),
('blog','Materials','Why 316 Stainless Steel Is Used in Process Instrumentation','why-316-stainless-steel-process-instrumentation','Molybdenum-bearing 316 stainless steel offers valuable corrosion resistance across many process environments.','<h2>Corrosion Performance</h2><p>316 stainless steel generally performs better than 304 in chloride-containing and many chemical environments, though exact suitability still depends on concentration and temperature.</p><h2>System Compatibility</h2><p>Material selection must consider tubing, valves, fittings, media, cleaning chemicals and external atmosphere as a complete system.</p>','https://www.hbfittings.net/uploads/33800/small/forged-316-stainless-steel-pipe-fittings532bc.png','2025-11-25 08:30:00',0,40,1,NOW(3),NOW(3));

INSERT INTO `videos` (`title`,`description`,`cover_url`,`video_url`,`sort`,`status`,`created_at`,`updated_at`) VALUES
('Inside the Depo Factory','A look at CNC machining, production organization and quality inspection.','https://www.hbfittings.net/uploads/33800/index/2.jpg','https://www.youtube.com/watch?v=WfXRP5cPMo8',10,1,NOW(3),NOW(3)),
('Pressure and Leakage Testing','See how valves and fittings are checked before shipment.','https://www.hbfittings.net/uploads/33800/index/3.jpg','https://www.youtube.com/watch?v=WfXRP5cPMo8',20,1,NOW(3),NOW(3)),
('OEM Product Development','From customer drawing and sample review to controlled production.','https://www.hbfittings.net/uploads/33800/index/4.jpg','https://www.youtube.com/watch?v=WfXRP5cPMo8',30,1,NOW(3),NOW(3)),
('Export Packing and Shipment','Protective packaging, labels and consolidated international shipping.','https://www.hbfittings.net/uploads/33800/index/8.jpg','https://www.youtube.com/watch?v=WfXRP5cPMo8',40,1,NOW(3),NOW(3));
